let g:gitgutter_override_sign_column_highlight = 0
let g:gitgutter_sign_added                     = '+'
let g:gitgutter_sign_modified                  = '~'
let g:gitgutter_sign_removed                   = '-'
let g:gitgutter_sign_removed_first_line        = '-'
let g:gitgutter_sign_modified_removed          = '~'
highlight GitGutterAdd    ctermfg=8
highlight GitGutterChange ctermfg=8
highlight GitGutterDelete ctermfg=8